# Generated by Django 2.2.3 on 2019-08-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20190807_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
