# Generated by Django 2.2.3 on 2019-08-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='userid',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
