# Generated by Django 2.2.3 on 2019-08-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_auto_20190808_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='userid',
            new_name='user',
        ),
    ]
