# Generated by Django 2.2.1 on 2019-07-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=25)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('num', models.IntegerField()),
                ('body', models.CharField(max_length=500)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
