# Generated by Django 2.2.3 on 2019-08-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=25)),
                ('pub_date', models.DateField(auto_now=True)),
                ('hit', models.PositiveIntegerField(default=0)),
                ('body', models.CharField(max_length=500)),
            ],
        ),
    ]
