# Generated by Django 2.2.1 on 2019-07-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20190710_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='file',
        ),
    ]
