# Generated by Django 2.2.1 on 2019-07-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_remove_notice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='num',
        ),
    ]
