# Generated by Django 2.2.1 on 2019-07-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_remove_notice_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
