# Generated by Django 2.2.1 on 2019-07-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_notice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
    ]
