# Generated by Django 2.2.1 on 2019-07-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_remove_notice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
