# Generated by Django 2.2.1 on 2019-07-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0009_auto_20190713_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
