# Generated by Django 2.2.3 on 2019-08-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('writer', models.CharField(default='admin', max_length=20)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('hits', models.IntegerField(default=0)),
                ('region', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=280)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('educated', models.CharField(max_length=250, null=True)),
                ('url', models.TextField(default='https://www.youthcenter.go.kr')),
            ],
            options={
                'ordering': ['-hits'],
            },
        ),
    ]
