# Generated by Django 2.2.3 on 2019-08-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('writer', models.CharField(default='admin', max_length=20)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('hits', models.IntegerField(default=0)),
                ('region', models.CharField(choices=[('서울', '서울'), ('인천', '인천'), ('경기', '경기')], max_length=20)),
                ('age', models.IntegerField(default=20)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('educated', models.CharField(choices=[('중졸 이상', '중졸 이상'), ('고졸 이상', '고졸 이상'), ('대졸 이상', '대졸 이상'), ('무관', '무관'), ('정보 없음', '정보 없음')], max_length=120, null=True)),
                ('regist_way', models.TextField(null=True)),
                ('url', models.TextField(default='https://www.youthcenter.go.kr')),
            ],
            options={
                'ordering': ['-hits'],
            },
        ),
    ]
