# Generated by Django 2.2.3 on 2019-08-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policylist',
            name='educated',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='policylist',
            name='region',
            field=models.CharField(max_length=120),
        ),
    ]
