# Generated by Django 2.2.3 on 2019-08-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policylist',
            name='regist_way',
        ),
        migrations.AlterField(
            model_name='policylist',
            name='age',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='policylist',
            name='educated',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='policylist',
            name='region',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='policylist',
            name='title',
            field=models.TextField(),
        ),
    ]
