# Generated by Django 2.2.3 on 2019-07-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policylist',
            name='hits',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='policylist',
            name='witer',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='policylist',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
