# Generated by Django 2.2.3 on 2019-07-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20190714_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policylist',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
