# Generated by Django 2.2.3 on 2019-08-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20190729_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='policylist',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='policylist',
            name='educated',
            field=models.CharField(choices=[('중졸 이상', '중졸 이상'), ('고졸 이상', '고졸 이상'), ('대졸 이상', '대졸 이상'), ('무관', '무관'), ('정보 없음', '정보 없음')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='policylist',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='policylist',
            name='regist_way',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='policylist',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='policylist',
            name='url',
            field=models.TextField(default='https://www.youthcenter.go.kr'),
        ),
    ]
