# Generated by Django 2.2.3 on 2019-07-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20190714_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policylist',
            old_name='witer',
            new_name='writer',
        ),
    ]
